import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ../../packages/contracts/src/types`.

export type Records = Models.Row & {
}
