services:
  nuxt:
    container_name: nuxt
    build: ./
    restart: always
    ports:
      - 3000:3000
    environment:
      - PUBLIC_URL=${PUBLIC_URL}

  # https://docs.directus.io/self-hosted/quickstart.html
  directus:
    container_name: directus
    image: directus/directus
    restart: always
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    env_file:
      - ./.env
