packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@supabase/supabase-js': '^2.57.4'
  '@types/node': '^22.16.5'
  '@types/react-dom': '^19.1.0'
  '@types/react': '^19.1.0'
  'astro': '^5.12.1'
  'eslint': '^9.31.0'
  'lucide-react': '^0.525.0'
  'react-dom': '^19.1.0'
  'react': '^19.1.0'
