import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./src/schemas`.

export type Entries = Models.Row & {
    title: string;
    done: boolean;
}
